// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohanpvidotaldycbuzyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oYW5wdmlkb3RhbGR5Y2J1enljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwNDMzODUsImV4cCI6MjA1NDYxOTM4NX0.za1m0QY4qrjKLX22pPxz8Ne3hKgZQjL5Cpn6Q32KdDA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);